### PR TITLE
`use-broadcast-channel` fix

### LINKED ISSUE #1130: BroadcastChannel gets closed before being used
https://github.com/FormidableLabs/spectacle/blob/00c337f62c22d0e8b1ffa1ec0ab45286fe760caa/src/hooks/use-broadcast-channel.ts#L25-L32

With React 18, in Strict Mode the effects are firing twice, which makes this code break as the channel is closed and then never opened again because the name is the same. Probably a better approach here would be to use a ref instead of state as it will also cause fewer re-renders.

I can make a pull request if needed.

### PR DESCRIPTION
**Pull request by gksander**
### Description

This PR tweaks `use-broadcast-channel` to use refs instead of state. With React 18 strict mode, effects run twice – and our existing effects setup was not setup to handle that. This PR stabilizes things a bit, and uses refs instead of state (since we don't need these pieces of data to trigger UI rerenders).

Fixes #1130 

#### Type of Change

Please delete options that are not relevant (including this descriptive text).

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

### Checklist: (Feel free to delete this section upon completion)

- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My code follows the style guidelines of this project (I have run `yarn format`)
- [x] New and existing unit tests pass locally with my changes (I have run `yarn test`)
- [x] My changes generate no new warnings
- [x] **I've tested this change manually in presenter mode.**

### CODE REVIEW

File: src/hooks/use-broadcast-channel.ts [hunk 1]
```diff
@@ -17,19 +17,16 @@ export default function useBroadcastChannel(
...
-    () => new BroadcastChannel(channelName)
-  );
+  const broadcasterId = useRef(() => ulid());
+  const channel = useRef<BroadcastChannel>();
 
   useEffect(() => {
-    if (channel.name !== channelName) {
-      setChannel(() => new BroadcastChannel(channelName));
-    }
+    channel.current = new BroadcastChannel(channelName);
```
Comment (gksander) [inline src/hooks/use-broadcast-channel.ts:24]: I don't think we really care about channel name check. Any time `channelName` changes, let's tear down the old channel and create a new one.

File: src/hooks/use-broadcast-channel.ts [hunk 2]
```diff
@@ -17,19 +17,16 @@ export default function useBroadcastChannel(
   onMessage: MessageCallback = noop,
   deps = []
 ) {
-  const [broadcasterId] = useState(() => ulid());
-  const [channel, setChannel] = useState(
-    () => new BroadcastChannel(channelName)
-  );
+  const broadcasterId = useRef(() => ulid());
```
Comment (carlos-kelly) [inline src/hooks/use-broadcast-channel.ts:20]: Do we need `ulid` with `useId()` in React 18?

Comment (gksander) [reply src/hooks/use-broadcast-channel.ts:20]: We have a React peer dep of `>= 17.0.2` (or something like that), so I think using a React-18 specific API would break that, no?

Comment (carlos-kelly) [reply src/hooks/use-broadcast-channel.ts:20]: Ah yes, not worth adjusting that here.
