### PR TITLE
Fix deck state transitions. Add test cases for deck state reducer.

### LINKED ISSUE #1287: Regression: using presenterMode causes slide transition animations not to function on display screen when steps are used
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

**What version of Spectacle are you using?** (can be found by running `npm list --depth 0 spectacle`)
10.1.4

**What version of React are you using?** (can be found by running `npm list --depth 0 react`)
18.2.0

**What browser are you using?** (e.g., Chrome 105.0.5195.102, Safari 16.0)
- Firefox  115.0
- Chrome 114.0.5735.198 

**What platform are you on?** (e.g., Windows, macOS, iOS, Android)
macOS

### Describe the Problem

1. Update the default TypeScript codesandbox to 10.1.4 and add a simple sequence component on a new slide such as
```js
const Sequence = () => {
  const { step, placeholder } = useSteps(2);

  return (
    <>
      {placeholder}
      <Heading>{step}</Heading>
    </>
  );
};
```
2. Copy the preview URL to two separate windows (so you're out of the Codesandbox sandbox)
a. One in presenter mode 
b. one in view mode
3. On the presenter mode transition through the slides

**Expected behavior:** The slides have a fade transition

**Actual behavior:** The slides have no transition but just disappear/appear

### Additional Information
Interestingly if the transition happens with input provided to the viewing window (rather than the presenter window) then the transition happens correctly and the slides fade.

When testing this in the 9.5.0 version of spectacle (which the sandbox linked is) it works as expected.

### PR DESCRIPTION
**Pull request by carloskelly13**
### Description

- Fixes transition animations not happening when a deck is controlled by a presenter mode view
- Adds test coverage for deck state reducer and util functions

https://github.com/FormidableLabs/spectacle/assets/1738349/5b982569-3f6f-4ff7-992a-d86c51b8afaa

Fixes #1287 

#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Run `pnpm run start:ts` and have a presenter mode (Cmd + K) and regular window open and verify transitions happen in the regular view.

### CODE REVIEW

File: packages/spectacle/src/hooks/use-deck-state.ts [hunk 1]
```diff
@@ -49,8 +50,15 @@ function deckReducer(state: DeckState, { type, payload = {} }: ReducerActions) {
         initialized: true
       };
     case 'SKIP_TO':
+      const navigationDirection = (() => {
+        if ('slideIndex' in payload && payload.slideIndex) {
+          return clamp(payload.slideIndex - state.activeView.slideIndex, -1, 1);
+        }
+        return null;
+      })();
```
Comment (carloskelly13) [inline packages/spectacle/src/hooks/use-deck-state.ts:58]: Doing a computed value in an iife since I need to type narrow `slideIndex` on `payload` since this reducer supports partial values.

**Review by gksander — APPROVED** [review]
awesome. love these test cases!
