### PR TITLE
fix name of prop and references to PropTypes

### LINKED ISSUE #906: The d.ts file needs minor fixes
In the d.ts file you can find a few wrong types and names.

**Expected behavior:**
- Deck's prop `animationsWhenGoingBack` is named correctly.
- Slide's `backgroundColor` has string type
- Slide's `backgroundImage` has string type
- Slide's `backgroundOpacity` has number type
- Slide's `backgroundPosition` has string type
- Slide's `backgroundRepeat` has string type
- Slide's `backgroundSize` has string type

**Actual behavior:** 
- Deck's `animationsWhenGoingBack` prop is named `animationsWhileGoingBack`
- The next Slide's props instead of typings have a reference to PropTypes:
  - backgroundColor
  - backgroundImage
  - backgroundOpacity
  - backgroundPosition
  - backgroundRepeat
  - backgroundSize

### PR DESCRIPTION
**Pull request by ronarvaez**
Minor fixes to the index.d.ts file

Fixes #906

#### Type of Change

Please delete options that are not relevant (including this descriptive text).

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?
built and tested locally
VScode intellisens shows the correct types.

### CODE REVIEW

File: index.d.ts [hunk 1]
```diff
@@ -35,12 +35,12 @@ declare module 'spectacle' {
   }>;
 
   export const Slide: React.FC<{
-    backgroundColor?: PropTypes.string;
```
Comment (kale-stew) [inline index.d.ts:38]: 🤦‍♀️  Oof. Great catch, @ronarvaez
