### PR TITLE
Fix autoPlayLoop

### LINKED ISSUE #1224: autoPlayLoop doesn't work
### Prerequisites

- [x] I have searched the open [issues](https://www.github.com/FormidableLabs/spectacle/issues) to make sure I'm not opening a duplicate issue
- [x] I have read through the [docs](https://www.formidable.com/open-source/spectacle/docs) before asking a question
- [x] I am using the latest version of Spectacle

### Describe Your Environment

**What version of Spectacle are you using?** (can be found by running `npm list --depth 0 spectacle`)
9.5.1

**What version of React are you using?** (can be found by running `npm list --depth 0 react`)
 react@18.1.0

**What browser are you using?** (e.g., Chrome 105.0.5195.102, Safari 16.0)
Version 105.0.5195.125 (Official Build) (arm64)

**What platform are you on?** (e.g., Windows, macOS, iOS, Android)
macOS

### Describe the Problem

**Expected behavior:** [What you expect to happen]

Just add autoPlayLoop to Deck (as in documentation) - expected to play slides in loop. 
Doesn't do so.

**Actual behavior:** [What actually happens]

Just add autoPlayLoop to Deck (as in documentation) - expected to play slides in loop. 
Doesn't do so.

### PR DESCRIPTION
**Pull request by fritz-c**
### Description

The `autoPlayLoop` prop did not actually make the slideshow loop when autoplaying.

The fix for that was fairly straightforward, but uncovered another bug - any `Appear` or `Stepper` components on the final slide would get skipped over when jumping from the final slide to the start. That required reworking the slide logic to wrap around to the start when the final step of the final slide was exceeded.

That again, was relatively straightforward, but uncovered another bug - animations occurring when wrapping from the end to the start of the slideshow were fairly rough, with slides coming and going seemingly randomly. A little work on existing internal logic fixed it for most cases, but due to the nature of the existing animation logic, I was unable to find a simple solution to the rough animations occurring when wrapping around with a two-slide presentation. It certainly is possible to rework the animations such that we don't need to make any compromises, but the scale of such a project went way beyond what I was prepared to do for this bugfix.

Fixes #1224

#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

I updated the existing `useAutoPlay` tests to account for the newer, simpler behavior of the hook, and added a new unit test to test `autoPlay`+`autoPlayLoop` behavior from the user's perspective.

### CODE REVIEW

File: packages/spectacle/src/components/slide/slide.tsx [hunk 1]
```diff
@@ -152,8 +154,36 @@ const Slide = (props: SlideProps): JSX.Element => {
...
+  const [isPassed, isUpcoming] = (() => {
+    // Handle special cases not covered by the main logic below
+    if (slideCount === 1) {
+      return [false, false];
+    }
+    if (slideCount === 2) {
+      // The 2-slide case results in some janky animation when wrapping from end
+      // to start, but that's the best overall behavior that could be achieved
+      // without majorly reworking the animation logic.
+      if (slideIndex === activeView.slideIndex) {
```
Comment (carlos-kelly) [inline packages/spectacle/src/components/slide/slide.tsx:167]: Good find on these small deck edge cases.

**Review by carlos-kelly — APPROVED** [review]
