### PR TITLE
Appear fixed when slide has id

### LINKED ISSUE #430: Appear breaks when slide has an id
For example, the following works:

```
        <Slide>
          <List>
            <ListItem>Item 1</ListItem>
            <Appear>
              <ListItem>Item 2</ListItem>
            </Appear>        
          </List>
        </Slide>
```

but the following doesn't:

```
        <Slide id="contents">
          <List>
            <ListItem>Item 1</ListItem>
            <Appear>
              <ListItem>Item 2</ListItem>
            </Appear>        
          </List>
        </Slide>
```

### PR DESCRIPTION
**Pull request by samwhale**
Fixes #430.

### CODE REVIEW

File: src/components/slide.js [hunk 1]
```diff
@@ -64,7 +64,7 @@ class Slide extends React.PureComponent {
               addFragment({
                 className: frag.className || '',
                 slide: this.props.hash,
-                id: `${this.props.slideIndex}-${currentOrder}`,
```
Comment (chrisbolin) [inline src/components/slide.js]: this is the key here: we were sometimes referring to fragments by their slide's index and other times by their slide's hash. Usually those two are the same. Until you set a custom slide id. 😄
